### PR TITLE
update gradle (and Kotlin), remove some deprecated API

### PR DESCRIPTION
**Pull request by imanushin**
The goal is to get rid of API which isn't supported by the latest Gradle (as per as it was released recently). The easiest way to do this is to use the latest Gradle for compilation.

### CODE REVIEW

**Comment by mouradxmt** [comment]
Can this be merged and published into a new release?

**Comment by alex-necula** [comment]
Bump

**Comment by mouradxmt** [comment]
Bump

**Comment by mouradxmt** [comment]
@imanushin can we merge this and trigger a release? this is blocking for upgrading to latest Gradle available.

**Comment by NikolayMetchev** [comment]
I suspect this plugin is no longer being maintained. Last commit was years ago

**Pull request merged**
